[package]
name = "ream-validator-lean"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["devnet2"]
devnet2 = [
    "ream-consensus-lean/devnet2",
    "ream-chain-lean/devnet2",
    "ream-fork-choice-lean/devnet2",
]
devnet3 = [
    "ream-consensus-lean/devnet3",
    "ream-chain-lean/devnet3",
    "ream-fork-choice-lean/devnet3",
]

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
ethereum_ssz.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
ssz_types.workspace = true
tokio.workspace = true
tracing = { workspace = true, features = ["log"] }
tree_hash.workspace = true

# ream dependencies
ream-chain-lean.workspace = true
ream-consensus-lean.workspace = true
ream-consensus-misc.workspace = true
ream-fork-choice-lean.workspace = true
ream-keystore.workspace = true
ream-metrics.workspace = true
ream-network-spec.workspace = true
ream-post-quantum-crypto.workspace = true
ream-sync.workspace = true

[lints]
workspace = true
