GENESIS_TIME: 1704085200
NUM_VALIDATORS: 3

# List of Genesis Validators' Public Keys
GENESIS_VALIDATORS:
  - 0xc5da8552d09453090b0b8f657fb3d947869bff30bd360058b52abe4fa75e820fb64f626db24f62529b6ff42526150e70da14fd09
  - 0x40ba5b575184d2004784836e21cc431898608f71fd4cfa1a0f2dae209183624b9bf71d1c4eebe867cf325e0fb8730e12e6b5011a
  - 0xe450cc485491a8476bbcae08b02d080e1bf00025a7e433796abbc433ceac841fa20bd742b1692679e3fc1b274bfd4a707407432c
