GENESIS_TIME: 1704085200
NUM_VALIDATORS: 3

# List of Genesis Validators' Public Keys
GENESIS_VALIDATORS:
  - 0x887ca91addda3a601d3d3c2ac22e6d001c65ae555e9d6312cda7ae12589084130710776ee8a8893bd583f7454297fb5b47e66f7b
  - 0xe9f39d309078160b6519c05224886b29e9e9a245b5a99c17a779895eaed5f9486b95d748a13f9866fe2a1d73896cb456165c503d
  - 0x9d35f76fbd1af5000156c0359fa44968136c275e7da17464238f8d6b1574807845abe17b6a62d94d7edf2246df156e21f0071e4b
