GENESIS_TIME: 1704085200
NUM_VALIDATORS: 3
GENESIS_VALIDATORS:
- 0x605065094422b9525f864d75d7dad0610f08b604513d112d5513e324f772411accb191097ea55e21733d221360b4407776b6e079
- 0x9661f8676e93b542deea3d6585cfb91c7f98b44c2a2bd225dc1fd44d0ad4d940b551aa10bcc5f50fb543b9135cbbc8247dfb6244
- 0xba43383d5dd7ff449468f47cfece54501fec7b77609cd6312e379d01d414df232b1742090d4e8202f95ebf47c57bf4148c98dc21
