[package]
name = "ream-rpc-lean"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["devnet1"]
devnet1 = [
    "ream-consensus-lean/devnet1",
    "ream-fork-choice-lean/devnet1",
    "ream-network-state-lean/devnet1",
]
devnet2 = [
    "ream-consensus-lean/devnet2",
    "ream-fork-choice-lean/devnet2",
    "ream-network-state-lean/devnet2",
]

[dependencies]
actix-web.workspace = true
ethereum_ssz.workspace = true
libp2p.workspace = true
parking_lot.workspace = true
tokio.workspace = true
tracing.workspace = true

#ream-dependencies
ream-api-types-common.workspace = true
ream-api-types-lean.workspace = true
ream-consensus-lean.workspace = true
ream-fork-choice-lean.workspace = true
ream-network-state-lean.workspace = true
ream-peer.workspace = true
ream-rpc-common.workspace = true
ream-storage.workspace = true

[lints]
workspace = true
